"""empty message

Revision ID: 574b20804fab
Revises: 7688bbf44c42
Create Date: 2018-09-13 03:36:35.165677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574b20804fab'
down_revision = '7688bbf44c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatetimestamp', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatetimestamp')
    # ### end Alembic commands ###
