"""empty message

Revision ID: d2eec0951614
Revises: 
Create Date: 2018-09-13 03:28:46.419197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2eec0951614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_enable', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updatetimestamp', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatetimestamp')
    op.drop_column('users', 'is_enable')
    # ### end Alembic commands ###
