"""empty message

Revision ID: f9bf3008dbeb
Revises: b3e0f3580dc1
Create Date: 2018-09-13 03:33:01.885406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9bf3008dbeb'
down_revision = 'b3e0f3580dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatetimestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatetimestamp', mysql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###
